config/routes.rb
Rails.application.routes.draw do
  resources :journals
  #GET, POST, PUT, PATCH, DELETE 
  devise_for :users
  #get 'home/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/journal.rb
class Journal < ApplicationRecord
  belongs_to :user
end

app/models/myjournal.rb
class Myjournal < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  #def index
  #end
#end
# class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1 or /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals or /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to journal_url(@journal), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to journal_url(@journal), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:title, :user_id)
    end
end

app/controllers/journals_controller.rb
class JournalsController < ApplicationController
  before_action :set_journal, only: %i[ show edit update destroy ]

  # GET /journals or /journals.json
  def index
    @journals = Journal.all
  end

  # GET /journals/1 or /journals/1.json
  def show
  end

  # GET /journals/new
  def new
    @journal = Journal.new
  end

  # GET /journals/1/edit
  def edit
  end

  # POST /journals or /journals.json
  def create
    @journal = Journal.new(journal_params)

    respond_to do |format|
      if @journal.save
        format.html { redirect_to journal_url(@journal), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @journal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /journals/1 or /journals/1.json
  def update
    respond_to do |format|
      if @journal.update(journal_params)
        format.html { redirect_to journal_url(@journal), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @journal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @journal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /journals/1 or /journals/1.json
  def destroy
    @journal.destroy

    respond_to do |format|
      format.html { redirect_to journals_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_journal
      @journal = Journal.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def journal_params
      params.require(:journal).permit(:title, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/journals_helper.rb
module JournalsHelper
end

app/views/home/index.html.erb
<!--<h1>My Book Journal</h1>
 <p>Find me in app/views/home/index.html.erb</p>
 
 app/views/home/index.html.erb 
<link rel="stylesheet" href="application.html.erb">
<p>Find me in app/views/home/index.html.erb</p> -->

<!-- app/views/home/index.html.erb -->
<%= stylesheet_link_tag "application" %>

<nav class="navbar navbar-expand-lg navbar-light bg-secondary">
  <div class="container">
    <a class="navbar-brand text-light" href="/new_journal">My Book Journal</a>
  </div>
</nav>

<div class="container"> 
  <h1>Books</h1>

  <div id="journals">
    <% @journals.each do |journal| %>
      <%= render journal %>
      <p>
        <%= link_to "Show this book", journal %>
      </p>
    <% end %>
  </div>

  <%= link_to "Add a new book", new_journal_path %>
</div>

<!-- Bootstrap JavaScript and Popper.js -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>

app/views/journals/_form.html.erb
<%= form_with(model: journal) do |form| %>
  <% if journal.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(journal.errors.count, "error") %> prohibited this journal from being saved:</h2>

      <ul>
        <% journal.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/journals/_journal.html.erb
<div id="<%= dom_id journal %>">
  <p>
    <strong>Book Title:</strong>
    <%= journal.title %>
  </p>

  <p>
    <strong>User:</strong>
    <%= journal.user_id %>
  </p>

</div>

app/views/journals/edit.html.erb
<h1>Editing journal</h1>

<%= render "form", journal: @journal %>

<br>

<div>
  <%= link_to "Show this journal", @journal %> |
  <%= link_to "Back to journals", journals_path %>
</div>

app/views/journals/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="journals">
  <% @journals.each do |journal| %>
    <%= render journal %>
    <p>
      <%= link_to "Show this book", journal %>
    </p>
  <% end %>

</div>

<%= link_to "Add a new book", new_journal_path %>

app/views/journals/new.html.erb
<h1>New journal</h1>

<%= render "form", journal: @journal %>

<br>

<div>
  <%= link_to "Back to journals", journals_path %>
</div>

app/views/journals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @journal %>

<div>
  <%= link_to "Edit this journal", edit_journal_path(@journal) %> |
  <%= link_to "Back to journals", journals_path %>

  <%= button_to "Destroy this journal", @journal, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>My Book Journal</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class='bg-dark text-light'>
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary">
      <div class="container">
        <a class="navbar-brand text-light" href="#">My Book Journal</a>
      </div>
    </nav>

    <div class="container"> 
      <div class="row">
        <div class="col-md-10 col-lg-8 offset-md-1 offset-lg-2">
          <div class="card mt-5">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap JavaScript and Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
  </body>
</html>

app/views/shared/_navar.html.erb
<!-- As a link -->
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
  </div>
</nav>

<!-- As a heading -->
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <span class="navbar-brand mb-0 h1">Navbar</span>
  </div>
</nav>